
#before_script:
# - export http_proxy=
# - export https_proxy=

#####################################################################
# WINDOWS
####################################################################

windows-x64-RelWithDebInfo-V140-SSE2-TBB:
  script: "scripts\\test.py platform:x64 build:RelWithDebInfo compiler:V140 isa:SSE2 tasking:TBB intensive:OFF"
  tags:   [win7, v140]

.windows-x64-RelWithDebInfo-V140-AVX2-TBB:
  script: "scripts\\test.py platform:x64 build:RelWithDebInfo compiler:V140 isa:AVX2 tasking:TBB intensive:OFF"
  tags:   [win7, v140]

.windows-x64-RelWithDebInfo-V120-AVX2-TBB:
  script: "scripts\\test.py platform:x64 build:RelWithDebInfo compiler:V120 isa:AVX2 tasking:TBB intensive:OFF"
  tags:   [win7, v120]

.windows-x64-RelWithDebInfo-ICC17-AVX2-TBB:
  script: "scripts\\test.py platform:x64 build:RelWithDebInfo compiler:ICC17 isa:AVX2 tasking:TBB intensive:OFF"
  tags:   [win7, icc17]
 
.windows-x64-RelWithDebInfo-CLANG-AVX2-TBB:
  script: "scripts\\test.py platform:x64 build:RelWithDebInfo compiler:CLANG isa:AVX2 tasking:TBB intensive:OFF"
  tags:   [win7, clang]


#####################################################################
# MACOSX
####################################################################

.macosx-x64-RelWithDebInfo-CLANG-SSE2-TBB:
  script: "scripts/test.py platform:x64 build:RelWithDebInfo compiler:CLANG isa:SSE2 tasking:TBB intensive:OFF"
  tags:   [mac, clang]
  
.macosx-x64-RelWithDebInfo-CLANG-AVX2-TBB:
  script: "scripts/test.py platform:x64 build:RelWithDebInfo compiler:CLANG isa:AVX2 tasking:TBB intensive:OFF"
  tags:   [mac, clang]

.macosx-x64-RelWithDebInfo-ICC16-AVX2-TBB:
  script: "scripts/test.py platform:x64 build:RelWithDebInfo compiler:ICC16 isa:AVX2 tasking:TBB intensive:OFF"
  tags:   [mac, icc16]


#####################################################################
# LINUX
####################################################################


.linux-x64-RelWithDebInfo-CLANG-SSE2-TBB:
  script: "scripts/test.py platform:x64 build:RelWithDebInfo compiler:CLANG isa:SSE2 tasking:TBB intensive:OFF"
  tags:   [linux, clang]
  
.linux-x64-RelWithDebInfo-CentOS6-SSE2-TBB:
  script: "scripts/test.py platform:x64 build:RelWithDebInfo compiler:GCC isa:SSE2 tasking:TBB intensive:OFF"
  tags:   [centos6]

.linux-x64-RelWithDebInfo-CLANG-AVX2-TBB:
  script: "scripts/test.py platform:x64 build:RelWithDebInfo compiler:CLANG isa:AVX2 tasking:TBB intensive:OFF"
  tags:   [linux, clang]

.linux-x64-RelWithDebInfo-GCC-AVX2-TBB:
  script: "scripts/test.py platform:x64 build:RelWithDebInfo compiler:GCC isa:AVX2 tasking:TBB intensive:OFF"
  tags:   [linux, gcc]

.linux-x64-RelWithDebInfo-ICC17-AVX512KNL-TBB:
  script: "scripts/test.py platform:x64 build:RelWithDebInfo compiler:ICC17 isa:AVX512KNL tasking:TBB intensive:OFF"
  tags:   [linux, icc17]

.linux-x64-RelWithDebInfo-ICC17-AVX2-TBB-KLOCKWORK:
  script: "scripts/test.py platform:x64 build:RelWithDebInfo compiler:ICC17 isa:AVX2 tasking:TBB klocwork:ON"
  tags:   [linux, icc17, klocwork]

.linux-knl-x64-RelWithDebInfo-ICC17-AVX512KNL-TBB:
  script: "scripts/test.py platform:x64 build:RelWithDebInfo compiler:ICC17 isa:AVX512KNL tasking:TBB intensive:OFF"
  tags:   [linux, knl, icc17]

.linux-knl-x64-RelWithDebInfo-CLANG4-AVX512KNL-TBB:
  script: "scripts/test.py platform:x64 build:RelWithDebInfo compiler:CLANG4 isa:AVX512KNL tasking:TBB intensive:OFF"
  tags:   [linux, knl, clang4]

.linux-skx-x64-RelWithDebInfo-ICC17-AVX512SKX-TBB:
  script: "scripts/test.py platform:x64 build:RelWithDebInfo compiler:ICC17 isa:AVX512SKX tasking:TBB intensive:OFF"
  tags:   [linux, skx, icc17]

.linux-skx-x64-RelWithDebInfo-CLANG4-AVX512SKX-TBB:
  script: "scripts/test.py platform:x64 build:RelWithDebInfo compiler:CLANG4 isa:AVX512SKX tasking:TBB intensive:OFF"
  tags:   [linux, skx, clang4]

#####################################################################
# WINDOWS
####################################################################

.windows-x64-RelWithDebInfo-V120-SSE2-TBB:
  script: "scripts\\test.py platform:x64 build:RelWithDebInfo compiler:V120 isa:SSE2 tasking:TBB intensive:ON"
  tags:   [win7, v120]

.windows-x64-RelWithDebInfo-V120-AVX-TBB:
  script: "scripts\\test.py platform:x64 build:RelWithDebInfo compiler:V120 isa:AVX tasking:INT intensive:ON"
  tags:   [win7, v120]
  
.windows-x64-RelWithDebInfo-V140-AVX2-TBB:
  script: "scripts\\test.py platform:x64 build:RelWithDebInfo compiler:V140 isa:AVX2 tasking:TBB intensive:ON"
  tags:   [win7, v140]

.windows-x64-RelWithDebInfo-V140-AVX2-TBB:
  script: "scripts\\test.py platform:x64 build:RelWithDebInfo compiler:V140 isa:AVX2 tasking:INT intensive:ON"
  tags:   [win7, v140]

.windows-x64-RelWithDebInfo-V140-AVX2-TBB:
  script: "scripts\\test.py platform:x64 build:RelWithDebInfo compiler:V140 isa:AVX2 tasking:PPL intensive:ON"
  tags:   [win7, v140]

.windows-x64-RelWithDebInfo-V141-AVX2-TBB:
  script: "scripts\\test.py platform:x64 build:RelWithDebInfo compiler:V140 isa:AVX2 tasking:TBB intensive:ON"
  tags:   [win7, v141]

.windows-x64-RelWithDebInfo-V141-AVX2-TBB-STATIC:
  script: "scripts\\test.py platform:x64 build:RelWithDebInfo compiler:V140 isa:AVX2 tasking:TBB STATIC_LIB=ON intensive:ON"
  tags:   [win7, v141]

.windows-x64-RelWithDebInfo-V140-AVX2-TBB:
  script: "scripts\\test.py platform:x64 build:RelWithDebInfo compiler:CLANG isa:AVX2 tasking:TBB intensive:ON"
  tags:   [win7, clang4]

.windows-x64-RelWithDebInfo-V140-AVX2-TBB:
  script: "scripts\\test.py platform:x64 build:RelWithDebInfo compiler:ICC16 isa:AVX2 tasking:TBB intensive:ON"
  tags:   [win7, icc16]

.windows-x64-RelWithDebInfo-ICC17-AVX2-TBB:
  script: "scripts\\test.py platform:x64 build:RelWithDebInfo compiler:ICC17 isa:AVX2 tasking:TBB intensive:ON"
  tags:   [win7, icc17]
  
.windows-x64-RelWithDebInfo-ICC17-AVX512SKX-TBB:
  script: "scripts\\test.py platform:x64 build:RelWithDebInfo compiler:ICC17 isa:AVX512SKX tasking:TBB intensive:ON sde:skx"
  tags:   [win7, icc17]

#####################################################################
# MACOSX
####################################################################

.macosx-x64-RelWithDebInfo-CLANG-SSE2-TBB:
  script: "scripts/test.py platform:x64 build:RelWithDebInfo compiler:CLANG isa:SSE2 tasking:TBB intensive:ON"
  tags:   [mac, clang]
  
.macosx-x64-RelWithDebInfo-CLANG-AVX-TBB:
  script: "scripts/test.py platform:x64 build:RelWithDebInfo compiler:CLANG isa:AVX tasking:TBB intensive:ON"
  tags:   [mac, clang]

.macosx-x64-RelWithDebInfo-CLANG-AVX2-TBB:
  script: "scripts/test.py platform:x64 build:RelWithDebInfo compiler:CLANG isa:AVX2 tasking:TBB intensive:ON"
  tags:   [mac, clang]

.macosx-x64-RelWithDebInfo-CLANG-AVX2-TBB-STATIC:
  script: "scripts/test.py platform:x64 build:RelWithDebInfo compiler:CLANG isa:AVX2 tasking:TBB STATIC_LIB:ON intensive:ON"
  tags:   [mac, clang]

.macosx-x64-RelWithDebInfo-ICC15-AVX-INT:
  script: "scripts/test.py platform:x64 build:RelWithDebInfo compiler:ICC15 isa:AVX tasking:INT intensive:ON"
  tags:   [mac, icc15]

.macosx-x64-RelWithDebInfo-ICC16-AVX-INT:
  script: "scripts/test.py platform:x64 build:RelWithDebInfo compiler:ICC16 isa:SSE2 tasking:TBB intensive:ON"
  tags:   [mac, icc16]


#####################################################################
# LINUX
####################################################################

.linux-x64-RelWithDebInfo-CLANG-SSE2-TBB:
  script: "scripts/test.py platform:x64 build:RelWithDebInfo compiler:CLANG isa:SSE2 tasking:TBB intensive:ON"
  tags:   [linux, clang]

.linux-x64-RelWithDebInfo-CLANG-AVX-TBB:
  script: "scripts/test.py platform:x64 build:RelWithDebInfo compiler:CLANG isa:AVX tasking:TBB intensive:ON"
  tags:   [linux, clang]

.linux-x64-RelWithDebInfo-CLANG-AVX2-TBB:
  script: "scripts/test.py platform:x64 build:RelWithDebInfo compiler:CLANG isa:AVX2 tasking:TBB intensive:ON memcheck:ON"
  tags:   [linux, clang]

.linux-x64-RelWithDebInfo-CLANG-AVX2-TBB-STATIC:
  script: "scripts/test.py platform:x64 build:RelWithDebInfo compiler:CLANG isa:AVX2 tasking:TBB STATIC_LIB:ON intensive:ON"
  tags:   [linux, clang]

.linux-x64-RelWithDebInfo-GCC-SSE2-TBB:
  script: "scripts/test.py platform:x64 build:RelWithDebInfo compiler:GCC isa:SSE2 tasking:TBB intensive:ON"
  tags:   [linux, gcc]

.linux-x64-RelWithDebInfo-GCC-AVX-TBB:
  script: "scripts/test.py platform:x64 build:RelWithDebInfo compiler:GCC isa:AVX tasking:TBB intensive:ON"
  tags:   [linux, gcc]

.linux-x64-RelWithDebInfo-GCC-AVX2-TBB:
  script: "scripts/test.py platform:x64 build:RelWithDebInfo compiler:GCC isa:AVX2 tasking:TBB intensive:ON"
  tags:   [linux, gcc]

.linux-x64-RelWithDebInfo-ICC15-SSE2-TBB:
  script: "scripts/test.py platform:x64 build:RelWithDebInfo compiler:ICC15 isa:SSE2 tasking:TBB intensive:ON"
  tags:   [linux, clang]

.linux-x64-RelWithDebInfo-ICC16-AVX-TBB:
  script: "scripts/test.py platform:x64 build:RelWithDebInfo compiler:ICC16 isa:AVX tasking:TBB intensive:ON"
  tags:   [linux, clang]

.linux-x64-RelWithDebInfo-ICC17-AVX2-TBB:
  script: "scripts/test.py platform:x64 build:RelWithDebInfo compiler:ICC17 isa:AVX2 tasking:TBB intensive:ON"
  tags:   [linux, clang]

.linux-x64-RelWithDebInfo-ICC18-AVX2-TBB:
  script: "scripts/test.py platform:x64 build:RelWithDebInfo compiler:ICC18 isa:AVX512SKX tasking:TBB intensive:ON"
  tags:   [linux, clang]

.linux-x64-RelWithDebInfo-CLANG-AVX2-TBB-NO-ISPC:
  script: "scripts/test.py platform:x64 build:RelWithDebInfo compiler:CLANG isa:AVX2 tasking:TBB ISPC_SUPPORT:OFF test:False"
  tags:   [linux, clang]

.linux-x64-RelWithDebInfo-CLANG-AVX2-TBB-NO-TUTORIALS:
  script: "scripts/test.py platform:x64 build:RelWithDebInfo compiler:CLANG isa:AVX2 tasking:TBB TUTORIALS:OFF test:False"
  tags:   [linux, clang]

.linux-x64-RelWithDebInfo-CLANG-AVX2-TBB-BACKFACECULLING:
  script: "scripts/test.py platform:x64 build:RelWithDebInfo compiler:CLANG isa:AVX2 tasking:TBB BACKFACE_CULLING:ON test:False"
  tags:   [linux, clang]

.linux-x64-RelWithDebInfo-CLANG-AVX2-TBB-IGNORE-INVALID-RAYS:
  script: "scripts/test.py platform:x64 build:RelWithDebInfo compiler:CLANG isa:AVX2 tasking:TBB IGNORE_INVALID_RAYS:ON test:False"
  tags:   [linux, clang]

.linux-x64-RelWithDebInfo-CLANG-AVX2-TBB-NO-INTERSECTION-FILTER:
  script: "scripts/test.py platform:x64 build:RelWithDebInfo compiler:CLANG isa:AVX2 tasking:TBB INTERSECTION_FILTER:OFF test:False"
  tags:   [linux, clang]

.linux-x64-RelWithDebInfo-CLANG-AVX2-TBB-RAYMASKS:
  script: "scripts/test.py platform:x64 build:RelWithDebInfo compiler:CLANG isa:AVX2 tasking:TBB RAY_MASK:ON test:False"
  tags:   [linux, clang]

.linux-x64-RelWithDebInfo-CLANG-AVX2-TBB-NO-PACKETS:
  script: "scripts/test.py platform:x64 build:RelWithDebInfo compiler:CLANG isa:AVX2 tasking:TBB RAY_PACKETS:OFF test:False"
  tags:   [linux, clang]

.linux-x64-RelWithDebInfo-CLANG-AVX2-TBB-STATCOUNTER:
  script: "scripts/test.py platform:x64 build:RelWithDebInfo compiler:CLANG isa:AVX2 tasking:TBB STAT_COUNTER:ON test:False"
  tags:   [linux, clang]


.linux-x64-RelWithDebInfo-CLANG4-ISAS-SSE2-TBB:
  script: "scripts/test.py platform:x64 build:RelWithDebInfo compiler:CLANG4 isa:[SSE2] tasking:TBB test:False"
  tags:   [linux, clang4]

.linux-x64-RelWithDebInfo-CLANG4-ISAS-SSE42-TBB:
  script: "scripts/test.py platform:x64 build:RelWithDebInfo compiler:CLANG4 isa:[SSE42] tasking:TBB test:False"
  tags:   [linux, clang4]

.linux-x64-RelWithDebInfo-CLANG4-ISAS-AVX-TBB:
  script: "scripts/test.py platform:x64 build:RelWithDebInfo compiler:CLANG4 isa:[AVX] tasking:TBB test:False"
  tags:   [linux, clang4]

.linux-x64-RelWithDebInfo-CLANG4-ISAS-AVX2-TBB:
  script: "scripts/test.py platform:x64 build:RelWithDebInfo compiler:CLANG4 isa:[AVX2] tasking:TBB test:False"
  tags:   [linux, clang4]

.linux-x64-RelWithDebInfo-CLANG4-ISAS-AVX512KNL-TBB:
  script: "scripts/test.py platform:x64 build:RelWithDebInfo compiler:CLANG4 isa:[AVX512KNL] tasking:TBB test:False"
  tags:   [linux, clang4]

.linux-x64-RelWithDebInfo-CLANG4-ISAS-AVX512SKX-TBB:
  script: "scripts/test.py platform:x64 build:RelWithDebInfo compiler:CLANG4 isa:[AVX512SKX] tasking:TBB test:False"
  tags:   [linux, clang4]


.linux-x64-RelWithDebInfo-CLANG4-AVX2-TBB-TRIS:
  script: "scripts/test.py platform:x64 build:RelWithDebInfo compiler:CLANG4 isa:AVX2 tasking:TBB TRIS:ON QUADS:OFF LINES:OFF HAIR:OFF SUBDIV:OFF USERGEOM:OFF test:False"
  tags:   [linux, clang4]

.linux-x64-RelWithDebInfo-CLANG4-AVX2-TBB-QUADS:
  script: "scripts/test.py platform:x64 build:RelWithDebInfo compiler:CLANG4 isa:AVX2 tasking:TBB TRIS:OFF QUADS:ON LINES:OFF HAIR:OFF SUBDIV:OFF USERGEOM:OFF test:False"
  tags:   [linux, clang4]

.linux-x64-RelWithDebInfo-CLANG4-AVX2-TBB-LINES:
  script: "scripts/test.py platform:x64 build:RelWithDebInfo compiler:CLANG4 isa:AVX2 tasking:TBB TRIS:ON QUADS:OFF LINES:ON HAIR:OFF SUBDIV:OFF USERGEOM:OFF test:False"
  tags:   [linux, clang4]

.linux-x64-RelWithDebInfo-CLANG4-AVX2-TBB-HAIR:
  script: "scripts/test.py platform:x64 build:RelWithDebInfo compiler:CLANG4 isa:AVX2 tasking:TBB TRIS:ON QUADS:OFF LINES:OFF HAIR:ON SUBDIV:OFF USERGEOM:OFF test:False"
  tags:   [linux, clang4]

.linux-x64-RelWithDebInfo-CLANG4-AVX2-TBB-SUBDIV:
  script: "scripts/test.py platform:x64 build:RelWithDebInfo compiler:CLANG4 isa:AVX2 tasking:TBB TRIS:ON QUADS:OFF LINES:OFF HAIR:OFF SUBDIV:ON USERGEOM:OFF test:False"
  tags:   [linux, clang4]

.linux-x64-RelWithDebInfo-CLANG4-AVX2-TBB-USERGEOM:
  script: "scripts/test.py platform:x64 build:RelWithDebInfo compiler:CLANG4 isa:AVX2 tasking:TBB TRIS:ON QUADS:OFF LINES:OFF HAIR:OFF SUBDIV:OFF USERGEOM:ON test:False"
  tags:   [linux, clang4]



